apiVersion: v1
kind: Service
metadata:
  name: kayenta
  labels:
    app: kayenta
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
    app: kayenta
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kayenta
  labels:
    app: kayenta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kayenta
  template:
    metadata:
      labels:
        app: kayenta
    spec:
      containers:
      - name: kayenta
        image: armory/kayenta:2.24.10
        ports:
        - containerPort: 8090
        env:
        - name: KAYENTA_OPTS
          value: "-Dspring.config.location=file:/opt/kayenta/config/my-config/kayenta.yml"
        - name: SPRING_APPLICATION_NAME
          value: "kayenta"
        - name: SPRING_CONFIG_NAME
          value: "kayenta"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /opt/kayenta/config/my-config
      volumes:
      - name: config
        configMap:
          name: kayenta-config
