apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kayenta-deployment.yml
  - redis-pod.yml
namespace: argo-rollouts
configMapGenerator:
  - name: kayenta-config
    files:
      - kayenta.yml
